/**
 * Parser tests
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { detectFormat } from '../src/parser/detector';
import { parse23andMe } from '../src/parser/23andme';
import { parseGenomeFile } from '../src/parser';

// Load test fixture
const sampleFile = readFileSync(
  join(__dirname, 'fixtures/sample-23andme.txt'),
  'utf-8'
);

describe('detectFormat', () => {
  it('detects 23andMe v5 format', () => {
    const format = detectFormat(sampleFile);
    expect(format).toBe('23andme-v5');
  });

  it('detects 23andMe from header comment', () => {
    const content = '# This data file generated by 23andMe at: Mon Aug 05\n';
    expect(detectFormat(content)).toBe('23andme-v5');
  });

  it('returns unknown for unrecognized format', () => {
    const content = 'some random content\nwithout headers';
    expect(detectFormat(content)).toBe('unknown');
  });
});

describe('parse23andMe', () => {
  it('parses sample file successfully', () => {
    const result = parse23andMe(sampleFile);
    expect(result.format).toBe('23andme-v5');
    expect(result.variants.length).toBe(15);
  });

  it('extracts metadata from header', () => {
    const result = parse23andMe(sampleFile);
    expect(result.metadata.generatedAt).toBe('Mon Aug 05 21:52:44 2024');
    expect(result.metadata.build).toBe('37');
  });

  it('parses variant data correctly', () => {
    const result = parse23andMe(sampleFile);
    const mthfr = result.variants.find(v => v.rsid === 'rs1801133');

    expect(mthfr).toBeDefined();
    expect(mthfr?.chromosome).toBe('1');
    expect(mthfr?.position).toBe(11856378);
    expect(mthfr?.genotype).toBe('CT');
  });

  it('handles no-call genotypes', () => {
    const result = parse23andMe(sampleFile);
    const noCall = result.variants.find(v => v.rsid === 'i713426');

    expect(noCall).toBeDefined();
    expect(noCall?.genotype).toBe('--');
  });

  it('normalizes rsid to lowercase', () => {
    const result = parse23andMe(sampleFile);
    result.variants.forEach(v => {
      expect(v.rsid).toBe(v.rsid.toLowerCase());
    });
  });

  it('normalizes genotype to uppercase', () => {
    const result = parse23andMe(sampleFile);
    result.variants.forEach(v => {
      expect(v.genotype).toBe(v.genotype.toUpperCase());
    });
  });

  it('throws error for empty file', () => {
    expect(() => parse23andMe('')).toThrow('No valid variants found');
  });

  it('throws error for file with only comments', () => {
    const content = '# comment 1\n# comment 2\n';
    expect(() => parse23andMe(content)).toThrow('No valid variants found');
  });
});

describe('parseGenomeFile', () => {
  it('auto-detects and parses 23andMe file', () => {
    const result = parseGenomeFile(sampleFile);
    expect(result.format).toBe('23andme-v5');
    expect(result.variants.length).toBeGreaterThan(0);
  });

  it('throws for unknown format', () => {
    const content = 'unknown format data';
    expect(() => parseGenomeFile(content)).toThrow('Unable to detect file format');
  });
});
